/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista3;
import modelo.Moto;

/**
 *
 * @author Usuaria
 */
public class frm_moto extends javax.swing.JFrame {

    /**
     * Creates new form frm_moto
     */
    public frm_moto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        velocidades = new javax.swing.JLabel();
        Tipo_moto = new javax.swing.JLabel();
        capacidad = new javax.swing.JLabel();
        placa = new javax.swing.JLabel();
        Chasis = new javax.swing.JLabel();
        serie = new javax.swing.JLabel();
        tipo = new javax.swing.JLabel();
        Marca = new javax.swing.JLabel();
        Modelo = new javax.swing.JLabel();
        color = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        motor = new javax.swing.JLabel();
        gasolina = new javax.swing.JLabel();
        peso = new javax.swing.JLabel();
        txt_velocidades = new javax.swing.JTextField();
        txt_moto = new javax.swing.JTextField();
        txt_capacidad = new javax.swing.JTextField();
        txt_placa = new javax.swing.JTextField();
        txt_chasis = new javax.swing.JTextField();
        txt_serie = new javax.swing.JTextField();
        txt_tipo = new javax.swing.JTextField();
        txt_marca = new javax.swing.JTextField();
        txt_modelo = new javax.swing.JTextField();
        txt_color = new javax.swing.JTextField();
        txt_precio = new javax.swing.JTextField();
        txt_motor = new javax.swing.JTextField();
        txt_gasolina = new javax.swing.JTextField();
        txt_peso = new javax.swing.JTextField();
        agregar = new javax.swing.JButton();
        txt_cilindros = new javax.swing.JTextField();
        cilindros = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Moto");

        velocidades.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        velocidades.setText("Velocidades");

        Tipo_moto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Tipo_moto.setText("Tipo de moto");

        capacidad.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        capacidad.setText("Capacidad");

        placa.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        placa.setText("Placa");

        Chasis.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Chasis.setText("Chasis");

        serie.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        serie.setText("Serie");

        tipo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tipo.setText("Tipo");

        Marca.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Marca.setText("Marca");

        Modelo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Modelo.setText("Modelo");

        color.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        color.setText("Color");

        precio.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        precio.setText("Precio");

        motor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        motor.setText("Motor");

        gasolina.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        gasolina.setText("TIpo de Gasolina");

        peso.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        peso.setText("Peso");

        txt_velocidades.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txt_moto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txt_capacidad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txt_placa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txt_chasis.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txt_serie.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txt_tipo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txt_marca.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txt_modelo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txt_color.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txt_precio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txt_motor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txt_gasolina.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txt_peso.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        agregar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        txt_cilindros.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        cilindros.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cilindros.setText("Cilindros");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(agregar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(velocidades)
                            .addComponent(Tipo_moto)
                            .addComponent(capacidad)
                            .addComponent(placa)
                            .addComponent(Chasis)
                            .addComponent(serie)
                            .addComponent(tipo)
                            .addComponent(Marca)
                            .addComponent(Modelo)
                            .addComponent(color)
                            .addComponent(precio)
                            .addComponent(motor)
                            .addComponent(gasolina)
                            .addComponent(peso)
                            .addComponent(cilindros))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_cilindros, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_chasis, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_capacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_moto, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_velocidades, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_serie, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_color, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_motor, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_gasolina, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_peso, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(velocidades)
                            .addComponent(txt_velocidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tipo_moto)
                            .addComponent(txt_moto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(capacidad)
                            .addComponent(txt_capacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(placa)
                            .addComponent(txt_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Chasis)
                            .addComponent(txt_chasis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(serie)
                            .addComponent(txt_serie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tipo)
                            .addComponent(txt_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Marca)
                            .addComponent(txt_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Modelo)
                            .addComponent(txt_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(color)
                            .addComponent(txt_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(precio)
                            .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(motor)
                            .addComponent(txt_motor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gasolina))
                    .addComponent(txt_gasolina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peso)
                    .addComponent(txt_peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cilindros)
                    .addComponent(txt_cilindros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(agregar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
        Moto mt = new Moto();
        
        mt.setVelocidades(this.txt_velocidades.getText());
        mt.setTipo_moto(this.txt_moto.getText());
        mt.setCapacidad(this.txt_capacidad.getText());
        mt.setPlaca(this.txt_placa.getText());
        mt.setChasis(this.txt_chasis.getText());
        mt.setSerie(this.txt_serie.getText());
        mt.setCilindros(this.txt_cilindros.getText());
        mt.setTipo(this.txt_tipo.getText());
        mt.setMarca(this.txt_marca.getText());
        mt.setModelo(this.txt_modelo.getText());
        mt.setColor(this.txt_color.getText());
        mt.setPrecio(this.txt_precio.getText());
        mt.setMotor(this.txt_motor.getText());
        mt.setGasolina(this.txt_gasolina.getText());
        mt.setPeso(this.txt_peso.getText());
            mt.agregar();
    }//GEN-LAST:event_agregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_moto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_moto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_moto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_moto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_moto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Chasis;
    private javax.swing.JLabel Marca;
    private javax.swing.JLabel Modelo;
    private javax.swing.JLabel Tipo_moto;
    private javax.swing.JButton agregar;
    private javax.swing.JLabel capacidad;
    private javax.swing.JLabel cilindros;
    private javax.swing.JLabel color;
    private javax.swing.JLabel gasolina;
    private javax.swing.JLabel motor;
    private javax.swing.JLabel peso;
    private javax.swing.JLabel placa;
    private javax.swing.JLabel precio;
    private javax.swing.JLabel serie;
    private javax.swing.JLabel tipo;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txt_capacidad;
    private javax.swing.JTextField txt_chasis;
    private javax.swing.JTextField txt_cilindros;
    private javax.swing.JTextField txt_color;
    private javax.swing.JTextField txt_gasolina;
    private javax.swing.JTextField txt_marca;
    private javax.swing.JTextField txt_modelo;
    private javax.swing.JTextField txt_moto;
    private javax.swing.JTextField txt_motor;
    private javax.swing.JTextField txt_peso;
    private javax.swing.JTextField txt_placa;
    private javax.swing.JTextField txt_precio;
    private javax.swing.JTextField txt_serie;
    private javax.swing.JTextField txt_tipo;
    private javax.swing.JTextField txt_velocidades;
    private javax.swing.JLabel velocidades;
    // End of variables declaration//GEN-END:variables
}
